apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react
  namespace: who-goes-to-try
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: react-app
        [cite_start]image: <DOCKER_USERNAME>/frontend-react:latest # Ganti dengan username Docker Hub kamu [cite: 171, 312]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: who-goes-to-try
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80