apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: who-goes-to-try-combined
  namespace: who-goes-to-try
spec:
  ingressClassName: traefik
  rules:
    - host: who-goes-to-try.hackathon.sev-2.com
      http:
        paths:
          # 1. ATURAN BACKEND (Wajib di atas)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: who-goes-to-try-backend
                port:
                  number: 3000
          # 2. ATURAN FRONTEND (Di bawah sebagai jalur utama)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: who-goes-to-try-frontend
                port:
                  number: 80
